spring:
  application:
    name: BE_Dupss

  datasource:
    url: jdbc:mysql://localhost:3306/dupss_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: dupss.system312@gmail.com
    password: kisrjwdiumujrcto
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25

  ai:
    openai:
      api-key: AIzaSyBJxuDyW4t6dJo44I0CYLnJ7IF36O9-nPQ
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash

app:
  jwtSecret: dupssSecretKey123456789012345678901234567890123456789012345678901234567890
  jwtExpirationMs: 86400000

jwt:
  secret-key: dupssSecretKey123456789012345678901234567890123456789012345678901234567890

cloudinary:
  name: dxkvlbzzu
  api_key: 415576174393987
  api_secret: FR9H84PhyIrD4gWc_BuOKD1Io5o

admin:
  username: admin
  password: Admin@123
  email: admin@dupss.com
